### ISSUE TITLE
data collection code missing

### ISSUE THREAD

**Issue by bharatprakash** [krishanrana/reskill#1]
can you add the data collection code to the repo?
python data/collect_demos.py --num_trajectories 40000 --subseq_len 10 --task block

also it would be nice to upload dataset somewhere and provide a link if possible.

**Comment by krishanrana** [comment]
thank you @bharatprakash for pointing this out. I have updated the .gitignore to include the necessary files and have additionally provided a download link to a pre-collected dataset.
